##---
# Source: skillhub/templates/deployment-config-os.yaml


apiVersion: v1
kind: DeploymentConfig

metadata:
    name: predictions
    labels:
        app: skillhub
        run: predictions

spec:
    replicas: 1
    selector:
        run: predictions
    template:
        metadata:
            labels:
                run: predictions
        spec:
            containers:
            - name: predictions
              image: docker-registry.default.svc:5000/skillhub/predictions:latest
              imagePullPolicy: Always
              ports:
              - containerPort: 5000

              env:
              - name: BACKEND_PORT
                value: "80"
              - name: BACKEND_HOST
                value: "backend-skillhub.apps.ic.gc.ca"
              - name: BACKEND_DATABASE_PORT
                value: "5432"
              - name: BACKEND_DATABASE_HOST
                value: "backend-database"
              - name: FRONTEND_PORT
                value: "80"
              - name: FRONTEND_HOST
                value: "skillhub.apps.ic.gc.ca"
              - name: PREDICTIONS_PORT
                value: "80"
              - name: PREDICTIONS_HOST
                value: "predictions-skillhub.apps.ic.gc.ca"
              - name: REDIS_PORT
                value: "6379"
              - name: REDIS_HOST
                value: "redis"
              - name: SCRAPER_PORT
                value: "80"
              - name: SCRAPER_HOST
                value: "scraper-skillhub.apps.ic.gc.ca"
              - name: SCRAPER_WORKER_PORT
                value: 
              - name: SCRAPER_WORKER_HOST
                value: 
              - name: SKILLHUB_API_KEY
                valueFrom:
                    secretKeyRef:
                        name: predictions-secrets
                        key: SKILLHUB_API_KEY

    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
          automatic: true
          containerNames:
          - predictions
          from:
              kind: ImageStreamTag
              name: "predictions:latest"
