##---
# Source: skillhub/templates/deployment-os.yaml


---
apiVersion: extensions/v1beta1
kind: Deployment

metadata:
    labels:
        app: skillhub
        run: redis
    name: redis

spec:
    replicas: 1
    selector:
        matchLabels:
            run: redis
    template:
        metadata:
            labels:
                run: redis
        spec:
            containers:
              - image: docker-registry.default.svc:5000/openshift/redis
                name: redis
                ports:
                  - containerPort: 6379

                env:
                  - name: BACKEND_PORT
                    value: "80"
                  - name: BACKEND_HOST
                    value: "backend-skillhub.apps.ic.gc.ca"
                  - name: BACKEND_DATABASE_PORT
                    value: "5432"
                  - name: BACKEND_DATABASE_HOST
                    value: "backend-database"
                  - name: FRONTEND_PORT
                    value: "80"
                  - name: FRONTEND_HOST
                    value: "skillhub.apps.ic.gc.ca"
                  - name: PREDICTIONS_PORT
                    value: "80"
                  - name: PREDICTIONS_HOST
                    value: "predictions-skillhub.apps.ic.gc.ca"
                  - name: REDIS_PORT
                    value: "6379"
                  - name: REDIS_HOST
                    value: "redis"
                  - name: SCRAPER_PORT
                    value: "80"
                  - name: SCRAPER_HOST
                    value: "scraper-skillhub.apps.ic.gc.ca"
                  - name: SCRAPER_WORKER_PORT
                    value: 
                  - name: SCRAPER_WORKER_HOST
                    value: 

