##---
# Source: skillhub/templates/service-os.yaml


apiVersion: v1
kind: Service

metadata:
    name: redis
    labels:
        app: skillhub
        run: redis

spec:
    type: ClusterIP
    selector:
        run: redis
    ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
