##---
# Source: skillhub/templates/deployment-config-os.yaml


apiVersion: v1
kind: DeploymentConfig

metadata:
    name: scraper-worker
    labels:
        app: skillhub
        run: scraper-worker

spec:
    replicas: 2
    selector:
        run: scraper-worker
    template:
        metadata:
            labels:
                run: scraper-worker
        spec:
            containers:
            - name: scraper-worker
              image: docker-registry.default.svc:5000/skillhub/scraper:latest
              imagePullPolicy: Always
              ports:
              - containerPort: 5000
              command:
                - "npm"
                - "run"
                - "worker"

              env:
              - name: BACKEND_PORT
                value: "80"
              - name: BACKEND_HOST
                value: "backend-skillhub.apps.ic.gc.ca"
              - name: BACKEND_DATABASE_PORT
                value: "5432"
              - name: BACKEND_DATABASE_HOST
                value: "backend-database"
              - name: FRONTEND_PORT
                value: "80"
              - name: FRONTEND_HOST
                value: "skillhub.apps.ic.gc.ca"
              - name: PREDICTIONS_PORT
                value: "80"
              - name: PREDICTIONS_HOST
                value: "predictions-skillhub.apps.ic.gc.ca"
              - name: REDIS_PORT
                value: "6379"
              - name: REDIS_HOST
                value: "redis"
              - name: SCRAPER_PORT
                value: "80"
              - name: SCRAPER_HOST
                value: "scraper-skillhub.apps.ic.gc.ca"
              - name: SCRAPER_WORKER_PORT
                value: 
              - name: SCRAPER_WORKER_HOST
                value: 
              - name: JIRA_HOST
                value: "http://jira.ic.gc.ca"
              - name: JIRA_PLATFORM
                value: "server"
              - name: BACKEND_PROTOCOL
                value: "https"
              - name: PROXY_HOST
                value: "cdhwg01.prod.prv"
              - name: PROXY_PORT
                value: "80"
              - name: JIRA_AUTH_TOKEN
                valueFrom:
                    secretKeyRef:
                        name: scraper-secrets
                        key: JIRA_AUTH_TOKEN
              - name: SKILLHUB_API_KEY
                valueFrom:
                    secretKeyRef:
                        name: scraper-secrets
                        key: SKILLHUB_API_KEY
            initContainers:
              - name: wait-for-service
                image: busybox
                command: ["sh", "-c", "until nslookup redis; do echo waiting for redis; sleep 2; done;"]

    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
          automatic: true
          containerNames:
          - scraper-worker
          from:
              kind: ImageStreamTag
              name: "scraper:latest"
