##---
# Source: skillhub/templates/service-os.yaml


apiVersion: v1
kind: Service

metadata:
    name: backend-database
    labels:
        app: skillhub
        run: backend-database

spec:
    type: ClusterIP
    selector:
        run: backend-database
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
