apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
    name: letsencrypt-production
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: devin@devinsit.com
        privateKeySecretRef:
            name: letsencrypt-production
        dns01:
            providers:
            - name: clouddns
              clouddns:
                  serviceAccountSecretRef:
                      name: clouddns-service-account
                      key: service-account.json
                  project: skillhub
