export {default as Landing} from "./Landing";
export {default as Login} from "./Login";
export {default as Onboarding} from "./Onboarding";
export {default as Profile} from "./Profile";
export {default as SignUp} from "./SignUp";
export {default as Search} from "./Search";
export {default as People} from "./People";
export {default as Projects} from "./Projects";
export {default as ProjectDetails} from "./ProjectDetails";
